### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by samulisoderlund** [Snipppppy/GW2-Simple-Timer#4]
I found the following typos in meta names:
 - Defeat Scarlet's minions ("minions" is lower-case, as opposed to other metas where every word is capitalized)
 - Ddoppelganger (double D)
 - Mawsof Torment (missing space between "Maws" and "of")
 - Icebrood Chmapions (Champions)
 - Defense of Amnitas (Amnytas)

edit: 
found additional typos in map names:
 - Iron Marsches (Iron Marches)
 - Amnitas (Amnytas)
 - Cristal Oasis (Crystal Oasis)

**Comment by Snipppppy** [comment]
Ty, fixed.
