### ISSUE TITLE
Wrong time on Forged with Fire.

### ISSUE THREAD

**Issue by Draconicrose** [Snipppppy/GW2-Simple-Timer#5]
Forged with Fire is off by 40 minutes.

![image](https://github.com/user-attachments/assets/d07d4050-bb22-4252-a23c-aaacd5924794)
![image](https://github.com/user-attachments/assets/59dac171-3011-402a-a428-9a1950df2d49)

**Comment by Snipppppy** [comment]
Tyvm, fixed
